{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/blogdemoapp-cursor/Pages/BlogMobileDemoDestination3_Products/Products_Edit.page",
    "_Type": "Action.Type.Navigation"
}