{
    "Target": {
        "EntitySet": "Products",
        "Service": "/blogdemoapp-cursor/Services/BlogMobileDemoDestination3.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/blogdemoapp-cursor/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/blogdemoapp-cursor/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}